### ISSUE TITLE
slack_usergroup_channels is broken

### ISSUE THREAD

**Issue by rlmartin** [jmatsu/terraform-provider-slack#46]
I haven't looked deeply into this, but the `slack_usergroup_channels` resource used to be working, but recently stopped working. I'm seeing errors like this:

```
Stack trace from the terraform-provider-slack_v0.7.0 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 71 [running]:
github.com/jmatsu/terraform-provider-slack/slack.resourceSlackUserGroupChannelsCreate(0xc000156a80, 0xeb38a0, 0xc0000affc0, 0x2, 0x1b0a160)
	github.com/jmatsu/terraform-provider-slack/slack/resource_usergroup_channels.go:54 +0x60c
github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0000f9000, 0xc0001df3b0, 0xc000626020, 0xeb38a0, 0xc0000affc0, 0xf56a01, 0xc00057bd78, 0xc00023c750)
│ Error: Plugin did not respond
│ 
│   with slack_usergroup_channels.foo,
│   on tf.json line 100, in resource.slack_usergroup_channels.foo:
│ 100:       },
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
	github.com/hashicorp/terraform@v0.12.13/helper/schema/resource.go:305 +0x365
github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0000f9080, 0xc00022d8a8, 0xc0001df3b0, 0xc000626020, 0xc00065da68, 0xc0000a1140, 0xf58c80)
	github.com/hashicorp/terraform@v0.12.13/helper/schema/provider.go:289 +0x99
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000a0a78, 0x137fdc0, 0xc000095f50, 0xc0001fdce0, 0xc0000a0a78, 0xc000095f50, 0xc00017da20)
	github.com/hashicorp/terraform@v0.12.13/helper/plugin/grpc_provider.go:885 +0x892
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x107c840, 0xc0000a0a78, 0x137fdc0, 0xc000095f50, 0xc0001df130, 0x0, 0x137fdc0, 0xc000095f50, 0xc0001940d0, 0xc1)
	github.com/hashicorp/terraform@v0.12.13/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a4a80, 0x138a640, 0xc000001500, 0xc000642900, 0xc000114330, 0x1acfa80, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.21.1/server.go:998 +0x46a
google.golang.org/grpc.(*Server).handleStream(0xc0000a4a80, 0x138a640, 0xc000001500, 0xc000642900, 0x0)
	google.golang.org/grpc@v1.21.1/server.go:1278 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004791e0, 0xc0000a4a80, 0x138a640, 0xc000001500, 0xc000642900)
	google.golang.org/grpc@v1.21.1/server.go:717 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.21.1/server.go:715 +0xa1

Error: The terraform-provider-slack_v0.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I believe my usage is pretty standard (though haven't simplified my code to prove it), something along the lines of:

```
    "slack_usergroup": {
      "ug": {
        "handle": "my-ug",
        "name": "My UG",
      }
    },
    "slack_conversation": {
      "convo1": {
        "is_private": true,
        "name": "convo1",
        "purpose": "purpose1",
        "topic": "topic1",
        "lifecycle": {
          "ignore_changes": [
            "topic",
            "purpose"
          ]
        }
      },
      "convo2": {
        "is_private": false,
        "name": "convo2",
        "purpose": "purpose2",
        "topic": "topic2",
        "lifecycle": {
          "ignore_changes": [
            "topic",
            "purpose"
          ]
        }
      },
    "slack_usergroup_channels": {
      "foo": {
        "channels": [
          "${slack_conversation.convo1.id}",
          "${slack_conversation.convo2.id}"
        ],
        "usergroup_id": "${slack_usergroup.ug.id}"
      }
```
 Not sure if you're seeing the same. Perhaps the API changed in some way.

**Comment by jmatsu** [comment]
It seems TypeList is just an array of `interface{}` in Go world but TypeSet is kinda `Set<interface{}>`. 
https://github.com/jmatsu/terraform-provider-slack/pull/45/files#diff-765bb593c455a457824d29c7cb45c7ff93e88022e988741a40371e12b240b293R31

I'll check this issue in this weekend or when i have spare time.
